import Head from 'next/head'
import { Inter } from 'next/font/google'
import Header from '@/components/Header';
import Achievements from "@/components/Achievements";
import Projects from "@/components/Projects";
import Technologies from "@/components/Technologies";
import Welcome from "@/components/Welcome";


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="flex w-full justify-center bg-lime-950">
        <div className="w-full md:w-4/5 l:w-3/5">
          <Welcome />
          <Projects />
          <Technologies />
          <Achievements />
        </div>
      </div>
    </>
  );
}
